#include "gpu_model/decode/generated_gcn_inst_db.h"

#include <vector>

namespace gpu_model {

const std::vector<GcnGeneratedFieldRef>& GeneratedGcnFieldRefs() {
  static const std::vector<GcnGeneratedFieldRef> kFieldRefs = {
  { "ssrc0", 0, 0, 8, false, "scalar source 0 selector" },
  { "ssrc1", 0, 8, 8, false, "scalar source 1 selector" },
  { "sdst", 0, 16, 7, false, "scalar destination register" },
  { "op", 0, 23, 7, false, "opcode selector" },
  { "enc", 0, 30, 2, false, "format encoding tag" },
  { "simm16", 0, 0, 16, true, "16-bit signed immediate" },
  { "sdst", 0, 16, 7, false, "scalar destination register" },
  { "op", 0, 23, 5, false, "opcode selector" },
  { "enc", 0, 28, 4, false, "format encoding tag" },
  { "ssrc0", 0, 0, 8, false, "scalar source selector or inline literal marker" },
  { "op", 0, 8, 8, false, "opcode selector" },
  { "sdst", 0, 16, 7, false, "scalar destination register" },
  { "enc", 0, 23, 9, false, "format encoding tag" },
  { "ssrc0", 0, 0, 8, false, "scalar source 0 selector" },
  { "ssrc1", 0, 8, 8, false, "scalar source 1 selector" },
  { "op", 0, 16, 7, false, "opcode selector" },
  { "enc", 0, 23, 9, false, "format encoding tag" },
  { "simm16", 0, 0, 16, true, "branch/control immediate" },
  { "op", 0, 16, 7, false, "opcode selector" },
  { "enc", 0, 23, 9, false, "format encoding tag" },
  { "offset", 0, 0, 8, false, "scalar memory offset or immediate field" },
  { "imm", 0, 8, 1, false, "offset immediate selector" },
  { "sbase", 0, 9, 6, false, "scalar base register pair selector" },
  { "sdst", 0, 15, 7, false, "scalar destination register or range base" },
  { "op_lo", 0, 22, 5, false, "opcode low bits" },
  { "op_hi", 0, 18, 2, false, "opcode high bits" },
  { "enc", 0, 27, 5, false, "format encoding tag" },
  { "src0", 0, 0, 9, false, "source 0 selector" },
  { "vsrc1", 0, 9, 8, false, "vector source 1 register" },
  { "vdst", 0, 17, 8, false, "vector destination register" },
  { "op", 0, 25, 6, false, "opcode selector" },
  { "enc", 0, 31, 1, false, "format encoding tag" },
  { "src0", 0, 0, 9, false, "source 0 selector" },
  { "op", 0, 9, 8, false, "opcode selector" },
  { "vdst", 0, 17, 8, false, "vector destination register" },
  { "enc", 0, 25, 7, false, "format encoding tag" },
  { "src0", 0, 0, 9, false, "source 0 selector" },
  { "vsrc1", 0, 9, 8, false, "vector source 1 register" },
  { "op", 0, 17, 8, false, "opcode selector" },
  { "enc", 0, 25, 7, false, "format encoding tag" },
  { "vdst", 0, 0, 8, false, "vector destination register" },
  { "abs", 0, 8, 3, false, "per-source abs modifiers" },
  { "clamp", 0, 11, 1, false, "result clamp modifier" },
  { "op", 0, 17, 9, false, "opcode selector" },
  { "enc", 0, 26, 6, false, "format encoding tag" },
  { "src0", 1, 0, 9, false, "source 0 selector" },
  { "src1", 1, 9, 9, false, "source 1 selector" },
  { "src2", 1, 18, 9, false, "source 2 selector" },
  { "omod", 1, 27, 2, false, "output modifier" },
  { "neg", 1, 29, 3, false, "per-source neg modifiers" },
  { "offset0", 0, 0, 8, false, "LDS offset 0" },
  { "offset1", 0, 8, 8, false, "LDS offset 1" },
  { "gds", 0, 16, 1, false, "GDS selector bit" },
  { "op", 0, 17, 8, false, "opcode selector" },
  { "enc", 0, 26, 6, false, "format encoding tag" },
  { "addr", 1, 0, 8, false, "address VGPR" },
  { "data0", 1, 8, 8, false, "data source 0 VGPR" },
  { "data1", 1, 16, 8, false, "data source 1 VGPR" },
  { "vdst", 1, 24, 8, false, "destination VGPR" },
  { "offset", 0, 0, 13, false, "flat/global offset" },
  { "lds", 0, 13, 1, false, "LDS path selector" },
  { "seg", 0, 14, 2, false, "segment selector" },
  { "glc", 0, 16, 1, false, "global coherency bit" },
  { "slc", 0, 17, 1, false, "system level coherency bit" },
  { "op", 0, 18, 7, false, "opcode selector" },
  { "enc", 0, 25, 6, false, "format encoding tag" },
  { "addr", 1, 0, 8, false, "address VGPR base" },
  { "data", 1, 8, 8, false, "data VGPR or source" },
  { "saddr", 1, 16, 7, false, "scalar address register selector" },
  { "nv", 1, 23, 1, false, "address component count flag" },
  { "vdst", 1, 24, 8, false, "destination VGPR" }
  };
  return kFieldRefs;
}

const std::vector<GcnGeneratedFormatDef>& GeneratedGcnFormatDefs() {
  static const std::vector<GcnGeneratedFormatDef> kFormatDefs = {
  { "sop2", GcnInstFormatClass::Sop2, 4, { "op", 0, 23, 7, false, "scalar SOP2 opcode" }, 0, 5 },
  { "sopk", GcnInstFormatClass::Sopk, 4, { "op", 0, 23, 5, false, "scalar SOPK opcode" }, 5, 4 },
  { "sop1", GcnInstFormatClass::Sop1, 4, { "op", 0, 8, 8, false, "scalar SOP1 opcode" }, 9, 4 },
  { "sopc", GcnInstFormatClass::Sopc, 4, { "op", 0, 16, 7, false, "scalar compare opcode" }, 13, 4 },
  { "sopp", GcnInstFormatClass::Sopp, 4, { "op", 0, 16, 7, false, "scalar branch/control opcode" }, 17, 3 },
  { "smrd", GcnInstFormatClass::Smrd, 8, { "op", 0, 22, 7, false, "scalar memory opcode (split field normalized)" }, 20, 7 },
  { "vop2", GcnInstFormatClass::Vop2, 4, { "op", 0, 25, 6, false, "vector VOP2 opcode" }, 27, 5 },
  { "vop1", GcnInstFormatClass::Vop1, 4, { "op", 0, 9, 8, false, "vector VOP1 opcode" }, 32, 4 },
  { "vopc", GcnInstFormatClass::Vopc, 4, { "op", 0, 17, 8, false, "vector compare opcode" }, 36, 4 },
  { "vop3a", GcnInstFormatClass::Vop3a, 8, { "op", 0, 17, 9, false, "vector VOP3A opcode" }, 40, 10 },
  { "ds", GcnInstFormatClass::Ds, 8, { "op", 0, 17, 8, false, "DS/LDS opcode" }, 50, 9 },
  { "flat", GcnInstFormatClass::Flat, 8, { "op", 0, 18, 7, false, "FLAT/GLOBAL opcode" }, 59, 12 }
  };
  return kFormatDefs;
}

const std::vector<GcnGeneratedInstDef>& GeneratedGcnInstDefs() {
  static const std::vector<GcnGeneratedInstDef> kInstDefs = {
  { 1, "gfx6_gfx8", GcnInstFormatClass::Sopp, 1, 4, "s_endpgm", "branch_or_sync", "branch_or_special" },
  { 2, "gfx6_gfx8", GcnInstFormatClass::Smrd, 0, 8, "s_load_dword", "scalar_memory", "scalar_alu_or_memory" },
  { 3, "gfx6_gfx8", GcnInstFormatClass::Smrd, 32, 8, "s_load_dwordx2", "scalar_memory", "scalar_alu_or_memory" },
  { 4, "gfx6_gfx8", GcnInstFormatClass::Smrd, 64, 8, "s_load_dwordx4", "scalar_memory", "scalar_alu_or_memory" },
  { 5, "gfx6_gfx8", GcnInstFormatClass::Sop2, 12, 4, "s_and_b32", "scalar_alu", "scalar_alu_or_memory" },
  { 6, "gfx6_gfx8", GcnInstFormatClass::Sop2, 36, 4, "s_mul_i32", "scalar_alu", "scalar_alu_or_memory" },
  { 7, "gfx6_gfx8", GcnInstFormatClass::Vop2, 52, 4, "v_add_u32_e32", "vector_alu", "vector_alu" },
  { 8, "gfx6_gfx8", GcnInstFormatClass::Vopc, 196, 4, "v_cmp_gt_i32_e32", "vector_compare", "vector_alu" },
  { 9, "gfx6_gfx8", GcnInstFormatClass::Sop1, 32, 4, "s_and_saveexec_b64", "scalar_alu", "scalar_alu_or_memory" },
  { 10, "gfx6_gfx8", GcnInstFormatClass::Sopp, 8, 4, "s_cbranch_execz", "branch_or_sync", "branch_or_special" },
  { 11, "gfx6_gfx8", GcnInstFormatClass::Vop2, 1, 4, "v_add_f32_e32", "vector_alu", "vector_alu" },
  { 12, "gfx6_gfx8", GcnInstFormatClass::Sopp, 12, 4, "s_waitcnt", "branch_or_sync", "branch_or_special" },
  { 13, "gfx6_gfx8", GcnInstFormatClass::Vop1, 1, 4, "v_mov_b32_e32", "vector_alu", "vector_alu" },
  { 14, "gfx6_gfx8", GcnInstFormatClass::Vop2, 17, 4, "v_ashrrev_i32_e32", "vector_alu", "vector_alu" },
  { 15, "gfx6_gfx8", GcnInstFormatClass::Vop2, 25, 4, "v_add_co_u32_e32", "vector_alu", "vector_alu" },
  { 16, "gfx6_gfx8", GcnInstFormatClass::Vop2, 28, 4, "v_addc_co_u32_e32", "vector_alu", "vector_alu" },
  { 17, "gfx6_gfx8", GcnInstFormatClass::Vop3a, 327, 8, "v_lshlrev_b64", "vector_alu", "vector_alu" },
  { 18, "gfx6_gfx8", GcnInstFormatClass::Flat, 20, 8, "global_load_dword", "vector_memory", "vector_memory" },
  { 19, "gfx6_gfx8", GcnInstFormatClass::Flat, 28, 8, "global_store_dword", "vector_memory", "vector_memory" },
  { 20, "gfx6_gfx8", GcnInstFormatClass::Sop2, 12, 8, "s_and_b32", "scalar_alu", "scalar_alu_or_memory" },
  { 21, "gfx6_gfx8", GcnInstFormatClass::Sopc, 4, 4, "s_cmp_lt_i32", "scalar_compare", "scalar_alu_or_memory" },
  { 22, "gfx6_gfx8", GcnInstFormatClass::Sopp, 5, 4, "s_cbranch_scc1", "branch_or_sync", "branch_or_special" },
  { 23, "gfx6_gfx8", GcnInstFormatClass::Sop2, 2, 4, "s_add_i32", "scalar_alu", "scalar_alu_or_memory" },
  { 24, "gfx6_gfx8", GcnInstFormatClass::Sopc, 6, 4, "s_cmp_eq_u32", "scalar_compare", "scalar_alu_or_memory" },
  { 25, "gfx6_gfx8", GcnInstFormatClass::Vop3a, 229, 8, "v_fma_f32", "vector_alu", "vector_alu" },
  { 26, "gfx6_gfx8", GcnInstFormatClass::Sopp, 4, 4, "s_cbranch_scc0", "branch_or_sync", "branch_or_special" },
  { 27, "gfx6_gfx8", GcnInstFormatClass::Sopp, 2, 4, "s_branch", "branch_or_sync", "branch_or_special" },
  { 28, "gfx6_gfx8", GcnInstFormatClass::Sop2, 15, 4, "s_or_b64", "scalar_alu", "scalar_alu_or_memory" },
  { 29, "gfx6_gfx8", GcnInstFormatClass::Sopp, 10, 4, "s_barrier", "branch_or_sync", "branch_or_special" },
  { 30, "gfx6_gfx8", GcnInstFormatClass::Ds, 13, 8, "ds_write_b32", "lds", "lds" },
  { 31, "gfx6_gfx8", GcnInstFormatClass::Ds, 54, 8, "ds_read_b32", "lds", "lds" },
  { 32, "gfx6_gfx8", GcnInstFormatClass::Vop1, 43, 4, "v_not_b32_e32", "vector_alu", "vector_alu" },
  { 33, "gfx6_gfx8", GcnInstFormatClass::Vop2, 18, 4, "v_lshlrev_b32_e32", "vector_alu", "vector_alu" },
  { 34, "gfx6_gfx8", GcnInstFormatClass::Vop3a, 254, 8, "v_lshl_add_u32", "vector_alu", "vector_alu" },
  { 35, "gfx6_gfx8", GcnInstFormatClass::Vop3a, 140, 8, "v_add_co_u32_e64", "vector_alu", "vector_alu" },
  { 36, "gfx6_gfx8", GcnInstFormatClass::Vop3a, 142, 8, "v_addc_co_u32_e64", "vector_alu", "vector_alu" },
  { 37, "gfx6_gfx8", GcnInstFormatClass::Vop1, 1, 8, "v_mov_b32_e32", "vector_alu", "vector_alu" },
  { 38, "gfx6_gfx8", GcnInstFormatClass::Vop3a, 98, 8, "v_cmp_gt_i32_e64", "vector_alu", "vector_alu" },
  { 39, "gfx6_gfx8", GcnInstFormatClass::Sopc, 8, 4, "s_cmp_gt_u32", "scalar_compare", "scalar_alu_or_memory" },
  { 40, "gfx6_gfx8", GcnInstFormatClass::Sopc, 10, 4, "s_cmp_lt_u32", "scalar_compare", "scalar_alu_or_memory" },
  { 41, "gfx6_gfx8", GcnInstFormatClass::Sop2, 11, 4, "s_cselect_b64", "scalar_alu", "scalar_alu_or_memory" },
  { 42, "gfx6_gfx8", GcnInstFormatClass::Sop2, 19, 4, "s_andn2_b64", "scalar_alu", "scalar_alu_or_memory" },
  { 43, "gfx6_gfx8", GcnInstFormatClass::Sopp, 6, 4, "s_cbranch_vccz", "branch_or_sync", "branch_or_special" },
  { 44, "gfx6_gfx8", GcnInstFormatClass::Vop2, 2, 4, "v_sub_f32_e32", "vector_alu", "vector_alu" },
  { 45, "gfx6_gfx8", GcnInstFormatClass::Vop2, 5, 8, "v_mul_f32_e32", "vector_alu", "vector_alu" },
  { 46, "gfx6_gfx8", GcnInstFormatClass::Vop2, 11, 4, "v_max_f32_e32", "vector_alu", "vector_alu" },
  { 47, "gfx6_gfx8", GcnInstFormatClass::Vop2, 59, 8, "v_fmac_f32_e32", "vector_alu", "vector_alu" },
  { 48, "gfx6_gfx8", GcnInstFormatClass::Vop2, 0, 4, "v_cndmask_b32_e32", "vector_alu", "vector_alu" },
  { 49, "gfx6_gfx8", GcnInstFormatClass::Vop1, 8, 4, "v_cvt_i32_f32_e32", "vector_alu", "vector_alu" },
  { 50, "gfx6_gfx8", GcnInstFormatClass::Vop1, 30, 4, "v_rndne_f32_e32", "vector_alu", "vector_alu" },
  { 51, "gfx6_gfx8", GcnInstFormatClass::Vop1, 32, 4, "v_exp_f32_e32", "vector_alu", "vector_alu" },
  { 52, "gfx6_gfx8", GcnInstFormatClass::Vop1, 34, 4, "v_rcp_f32_e32", "vector_alu", "vector_alu" },
  { 53, "gfx6_gfx8", GcnInstFormatClass::Sop1, 0, 4, "s_mov_b32", "scalar_alu", "scalar_alu_or_memory" },
  { 54, "gfx6_gfx8", GcnInstFormatClass::Sop1, 0, 8, "s_mov_b32", "scalar_alu", "scalar_alu_or_memory" },
  { 55, "gfx6_gfx8", GcnInstFormatClass::Sop2, 30, 4, "s_lshr_b32", "scalar_alu", "scalar_alu_or_memory" },
  { 56, "gfx6_gfx8", GcnInstFormatClass::Vopc, 204, 4, "v_cmp_gt_u32_e32", "vector_compare", "vector_alu" },
  { 57, "gfx6_gfx8", GcnInstFormatClass::Vopc, 75, 4, "v_cmp_ngt_f32_e32", "vector_compare", "vector_alu" },
  { 58, "gfx6_gfx8", GcnInstFormatClass::Vopc, 78, 4, "v_cmp_nlt_f32_e32", "vector_compare", "vector_alu" },
  { 59, "gfx6_gfx8", GcnInstFormatClass::Vop3a, 128, 8, "v_cndmask_b32_e64", "vector_alu", "vector_alu" },
  { 60, "gfx6_gfx8", GcnInstFormatClass::Vop3a, 239, 8, "v_div_fixup_f32", "vector_alu", "vector_alu" },
  { 61, "gfx6_gfx8", GcnInstFormatClass::Vop3a, 240, 8, "v_div_scale_f32", "vector_alu", "vector_alu" },
  { 62, "gfx6_gfx8", GcnInstFormatClass::Vop3a, 241, 8, "v_div_fmas_f32", "vector_alu", "vector_alu" },
  { 63, "gfx6_gfx8", GcnInstFormatClass::Vop3a, 324, 8, "v_ldexp_f32", "vector_alu", "vector_alu" },
  { 64, "gfx6_gfx8", GcnInstFormatClass::Vop2, 5, 4, "v_mul_f32_e32", "vector_alu", "vector_alu" },
  { 65, "gfx6_gfx8", GcnInstFormatClass::Vop2, 59, 4, "v_fmac_f32_e32", "vector_alu", "vector_alu" },
  { 66, "gfx6_gfx8", GcnInstFormatClass::Vopc, 202, 4, "v_cmp_eq_u32_e32", "vector_compare", "vector_alu" },
  { 67, "gfx6_gfx8", GcnInstFormatClass::Vop3a, 482, 8, "v_mfma_f32_16x16x4f32", "vector_alu", "vector_alu" },
  { 68, "gfx6_gfx8", GcnInstFormatClass::Sopp, 0, 4, "s_nop", "branch_or_sync", "branch_or_special" },
  { 69, "gfx6_gfx8", GcnInstFormatClass::Sop2, 0, 4, "s_add_u32", "scalar_alu", "scalar_alu_or_memory" },
  { 70, "gfx6_gfx8", GcnInstFormatClass::Sop2, 4, 4, "s_addc_u32", "scalar_alu", "scalar_alu_or_memory" },
  { 71, "gfx6_gfx8", GcnInstFormatClass::Sop1, 1, 4, "s_mov_b64", "scalar_alu", "scalar_alu_or_memory" },
  { 72, "gfx6_gfx8", GcnInstFormatClass::Sop2, 32, 4, "s_ashr_i32", "scalar_alu", "scalar_alu_or_memory" },
  { 73, "gfx6_gfx8", GcnInstFormatClass::Sop2, 29, 4, "s_lshl_b64", "scalar_alu", "scalar_alu_or_memory" },
  { 74, "gfx6_gfx8", GcnInstFormatClass::Sopp, 9, 4, "s_cbranch_execnz", "branch_or_sync", "branch_or_special" },
  { 75, "gfx6_gfx8", GcnInstFormatClass::Vopc, 195, 4, "v_cmp_le_i32_e32", "vector_compare", "vector_alu" },
  { 76, "gfx6_gfx8", GcnInstFormatClass::Vopc, 193, 4, "v_cmp_lt_i32_e32", "vector_compare", "vector_alu" },
  { 77, "gfx6_gfx8", GcnInstFormatClass::Sop2, 13, 4, "s_and_b64", "scalar_alu", "scalar_alu_or_memory" },
  { 78, "gfx6_gfx8", GcnInstFormatClass::Sopk, 0, 4, "s_movk_i32", "scalar_alu", "scalar_alu_or_memory" },
  { 79, "gfx6_gfx8", GcnInstFormatClass::Vop3a, 244, 8, "v_mad_u64_u32", "vector_alu", "vector_alu" },
  { 80, "gfx6_gfx8", GcnInstFormatClass::Vop1, 5, 4, "v_cvt_f32_i32_e32", "vector_alu", "vector_alu" },
  { 81, "gfx6_gfx8", GcnInstFormatClass::Vop3a, 326, 8, "v_mbcnt_lo_u32_b32", "vector_alu", "vector_alu" },
  { 82, "gfx6_gfx8", GcnInstFormatClass::Vop3a, 326, 8, "v_mbcnt_hi_u32_b32", "vector_alu", "vector_alu" },
  { 83, "gfx6_gfx8", GcnInstFormatClass::Sop1, 13, 4, "s_bcnt1_i32_b64", "scalar_alu", "scalar_alu_or_memory" },
  { 84, "gfx6_gfx8", GcnInstFormatClass::Flat, 66, 8, "global_atomic_add", "vector_memory", "vector_memory" }
  };
  return kInstDefs;
}

const std::vector<GcnInstEncodingDef>& GeneratedGcnEncodingDefs() {
  static const std::vector<GcnInstEncodingDef> kEncodingDefs = {
  { 1, GcnInstFormatClass::Sopp, 1, 4, "s_endpgm" },
  { 2, GcnInstFormatClass::Smrd, 0, 8, "s_load_dword" },
  { 3, GcnInstFormatClass::Smrd, 32, 8, "s_load_dwordx2" },
  { 4, GcnInstFormatClass::Smrd, 64, 8, "s_load_dwordx4" },
  { 5, GcnInstFormatClass::Sop2, 12, 4, "s_and_b32" },
  { 6, GcnInstFormatClass::Sop2, 36, 4, "s_mul_i32" },
  { 7, GcnInstFormatClass::Vop2, 52, 4, "v_add_u32_e32" },
  { 8, GcnInstFormatClass::Vopc, 196, 4, "v_cmp_gt_i32_e32" },
  { 9, GcnInstFormatClass::Sop1, 32, 4, "s_and_saveexec_b64" },
  { 10, GcnInstFormatClass::Sopp, 8, 4, "s_cbranch_execz" },
  { 11, GcnInstFormatClass::Vop2, 1, 4, "v_add_f32_e32" },
  { 12, GcnInstFormatClass::Sopp, 12, 4, "s_waitcnt" },
  { 13, GcnInstFormatClass::Vop1, 1, 4, "v_mov_b32_e32" },
  { 14, GcnInstFormatClass::Vop2, 17, 4, "v_ashrrev_i32_e32" },
  { 15, GcnInstFormatClass::Vop2, 25, 4, "v_add_co_u32_e32" },
  { 16, GcnInstFormatClass::Vop2, 28, 4, "v_addc_co_u32_e32" },
  { 17, GcnInstFormatClass::Vop3a, 327, 8, "v_lshlrev_b64" },
  { 18, GcnInstFormatClass::Flat, 20, 8, "global_load_dword" },
  { 19, GcnInstFormatClass::Flat, 28, 8, "global_store_dword" },
  { 20, GcnInstFormatClass::Sop2, 12, 8, "s_and_b32" },
  { 21, GcnInstFormatClass::Sopc, 4, 4, "s_cmp_lt_i32" },
  { 22, GcnInstFormatClass::Sopp, 5, 4, "s_cbranch_scc1" },
  { 23, GcnInstFormatClass::Sop2, 2, 4, "s_add_i32" },
  { 24, GcnInstFormatClass::Sopc, 6, 4, "s_cmp_eq_u32" },
  { 25, GcnInstFormatClass::Vop3a, 229, 8, "v_fma_f32" },
  { 26, GcnInstFormatClass::Sopp, 4, 4, "s_cbranch_scc0" },
  { 27, GcnInstFormatClass::Sopp, 2, 4, "s_branch" },
  { 28, GcnInstFormatClass::Sop2, 15, 4, "s_or_b64" },
  { 29, GcnInstFormatClass::Sopp, 10, 4, "s_barrier" },
  { 30, GcnInstFormatClass::Ds, 13, 8, "ds_write_b32" },
  { 31, GcnInstFormatClass::Ds, 54, 8, "ds_read_b32" },
  { 32, GcnInstFormatClass::Vop1, 43, 4, "v_not_b32_e32" },
  { 33, GcnInstFormatClass::Vop2, 18, 4, "v_lshlrev_b32_e32" },
  { 34, GcnInstFormatClass::Vop3a, 254, 8, "v_lshl_add_u32" },
  { 35, GcnInstFormatClass::Vop3a, 140, 8, "v_add_co_u32_e64" },
  { 36, GcnInstFormatClass::Vop3a, 142, 8, "v_addc_co_u32_e64" },
  { 37, GcnInstFormatClass::Vop1, 1, 8, "v_mov_b32_e32" },
  { 38, GcnInstFormatClass::Vop3a, 98, 8, "v_cmp_gt_i32_e64" },
  { 39, GcnInstFormatClass::Sopc, 8, 4, "s_cmp_gt_u32" },
  { 40, GcnInstFormatClass::Sopc, 10, 4, "s_cmp_lt_u32" },
  { 41, GcnInstFormatClass::Sop2, 11, 4, "s_cselect_b64" },
  { 42, GcnInstFormatClass::Sop2, 19, 4, "s_andn2_b64" },
  { 43, GcnInstFormatClass::Sopp, 6, 4, "s_cbranch_vccz" },
  { 44, GcnInstFormatClass::Vop2, 2, 4, "v_sub_f32_e32" },
  { 45, GcnInstFormatClass::Vop2, 5, 8, "v_mul_f32_e32" },
  { 46, GcnInstFormatClass::Vop2, 11, 4, "v_max_f32_e32" },
  { 47, GcnInstFormatClass::Vop2, 59, 8, "v_fmac_f32_e32" },
  { 48, GcnInstFormatClass::Vop2, 0, 4, "v_cndmask_b32_e32" },
  { 49, GcnInstFormatClass::Vop1, 8, 4, "v_cvt_i32_f32_e32" },
  { 50, GcnInstFormatClass::Vop1, 30, 4, "v_rndne_f32_e32" },
  { 51, GcnInstFormatClass::Vop1, 32, 4, "v_exp_f32_e32" },
  { 52, GcnInstFormatClass::Vop1, 34, 4, "v_rcp_f32_e32" },
  { 53, GcnInstFormatClass::Sop1, 0, 4, "s_mov_b32" },
  { 54, GcnInstFormatClass::Sop1, 0, 8, "s_mov_b32" },
  { 55, GcnInstFormatClass::Sop2, 30, 4, "s_lshr_b32" },
  { 56, GcnInstFormatClass::Vopc, 204, 4, "v_cmp_gt_u32_e32" },
  { 57, GcnInstFormatClass::Vopc, 75, 4, "v_cmp_ngt_f32_e32" },
  { 58, GcnInstFormatClass::Vopc, 78, 4, "v_cmp_nlt_f32_e32" },
  { 59, GcnInstFormatClass::Vop3a, 128, 8, "v_cndmask_b32_e64" },
  { 60, GcnInstFormatClass::Vop3a, 239, 8, "v_div_fixup_f32" },
  { 61, GcnInstFormatClass::Vop3a, 240, 8, "v_div_scale_f32" },
  { 62, GcnInstFormatClass::Vop3a, 241, 8, "v_div_fmas_f32" },
  { 63, GcnInstFormatClass::Vop3a, 324, 8, "v_ldexp_f32" },
  { 64, GcnInstFormatClass::Vop2, 5, 4, "v_mul_f32_e32" },
  { 65, GcnInstFormatClass::Vop2, 59, 4, "v_fmac_f32_e32" },
  { 66, GcnInstFormatClass::Vopc, 202, 4, "v_cmp_eq_u32_e32" },
  { 67, GcnInstFormatClass::Vop3a, 482, 8, "v_mfma_f32_16x16x4f32" },
  { 68, GcnInstFormatClass::Sopp, 0, 4, "s_nop" },
  { 69, GcnInstFormatClass::Sop2, 0, 4, "s_add_u32" },
  { 70, GcnInstFormatClass::Sop2, 4, 4, "s_addc_u32" },
  { 71, GcnInstFormatClass::Sop1, 1, 4, "s_mov_b64" },
  { 72, GcnInstFormatClass::Sop2, 32, 4, "s_ashr_i32" },
  { 73, GcnInstFormatClass::Sop2, 29, 4, "s_lshl_b64" },
  { 74, GcnInstFormatClass::Sopp, 9, 4, "s_cbranch_execnz" },
  { 75, GcnInstFormatClass::Vopc, 195, 4, "v_cmp_le_i32_e32" },
  { 76, GcnInstFormatClass::Vopc, 193, 4, "v_cmp_lt_i32_e32" },
  { 77, GcnInstFormatClass::Sop2, 13, 4, "s_and_b64" },
  { 78, GcnInstFormatClass::Sopk, 0, 4, "s_movk_i32" },
  { 79, GcnInstFormatClass::Vop3a, 244, 8, "v_mad_u64_u32" },
  { 80, GcnInstFormatClass::Vop1, 5, 4, "v_cvt_f32_i32_e32" },
  { 81, GcnInstFormatClass::Vop3a, 326, 8, "v_mbcnt_lo_u32_b32" },
  { 82, GcnInstFormatClass::Vop3a, 326, 8, "v_mbcnt_hi_u32_b32" },
  { 83, GcnInstFormatClass::Sop1, 13, 4, "s_bcnt1_i32_b64" },
  { 84, GcnInstFormatClass::Flat, 66, 8, "global_atomic_add" }
  };
  return kEncodingDefs;
}

}  // namespace gpu_model
