#include "gpu_model/instruction/encoded/internal/generated_encoded_gcn_inst_db.h"

#include <vector>

namespace gpu_model {

const std::vector<GcnGeneratedProfileDef>& GeneratedGcnProfileDefs() {
  static const std::vector<GcnGeneratedProfileDef> kProfileDefs = {
  { "gfx6_gfx8", "GCN gfx6-gfx8", 64, false, "legacy" },
  { "gfx9_cdna", "gfx9+/CDNA", 64, true, "gfx9" }
  };
  return kProfileDefs;
}

const std::vector<GcnGeneratedOperandKindDef>& GeneratedGcnOperandKindDefs() {
  static const std::vector<GcnGeneratedOperandKindDef> kOperandKindDefs = {
  { "scalar_reg", "scalar", "scalar register operand" },
  { "scalar_reg_range", "scalar", "scalar register range operand" },
  { "scalar_reg_pair_dest", "scalar", "7-bit scalar destination field decoded as register pair or special pair register" },
  { "scalar_src8", "scalar", "8-bit scalar source selector decoded with inline constant rules" },
  { "scalar_src8_pair", "scalar", "8-bit scalar source selector decoded as register pair or special pair register" },
  { "vector_reg", "vector", "vector register operand" },
  { "vector_reg_range", "vector", "vector register range operand" },
  { "special_reg", "special", "special architectural register operand" },
  { "immediate", "immediate", "inline or decoded immediate operand" },
  { "immediate_field", "immediate", "immediate directly decoded from a named bitfield" },
  { "immediate_literal32", "immediate", "32-bit literal immediate carried in the second instruction word" },
  { "simm16", "immediate", "signed 16-bit immediate field" },
  { "src9", "generic", "9-bit source selector decoded with scalar/vector/immediate rules" },
  { "branch_target", "control", "branch target or branch immediate operand" },
  { "waitcnt_fields", "control", "decoded waitcnt domain thresholds" },
  { "flat_addr", "memory", "flat/global address operand decoded from addr plus optional scalar address pair" },
  { "flat_offset13", "immediate", "signed 13-bit flat/global offset field" },
  { "vop3_sdst_pair", "scalar", "scalar destination pair encoded in VOP3 low-word control bits" },
  { "vop3_src2_pair", "scalar", "scalar register pair encoded from the VOP3 src2 field" },
  { "vector_reg_range_field", "vector", "vector register range decoded from a named field using reg_count" },
  { "src9_or_vector_reg_range2", "generic", "VOP3 source selector decoded as src9 or vector register range of 2 when encoded as vector pair" }
  };
  return kOperandKindDefs;
}

const std::vector<GcnGeneratedSemanticFamilyDef>& GeneratedGcnSemanticFamilyDefs() {
  static const std::vector<GcnGeneratedSemanticFamilyDef> kSemanticFamilyDefs = {
  { "scalar_alu", "compute", "scalar arithmetic and logic" },
  { "scalar_compare", "control", "scalar compare and condition code update" },
  { "scalar_memory", "memory", "scalar memory access" },
  { "branch_or_sync", "sync", "scalar branch or synchronization control" },
  { "vector_alu", "compute", "vector arithmetic and logic" },
  { "vector_compare", "control", "vector compare and mask-producing operations" },
  { "vector_memory", "memory", "vector/global/flat memory operations" },
  { "lds", "memory", "local data share operations" },
  { "special", "control", "export, interpolation, special or not-yet-grouped operations" }
  };
  return kSemanticFamilyDefs;
}

const std::vector<GcnGeneratedImplicitRegRef>& GeneratedGcnImplicitRegRefs() {
  static const std::vector<GcnGeneratedImplicitRegRef> kImplicitRegRefs = {
  { "exec", false },
  { "exec", false },
  { "exec", false },
  { "scc", false },
  { "scc", false },
  { "exec", false },
  { "exec", false },
  { "exec", false },
  { "exec", false },
  { "exec", false },
  { "exec", false },
  { "exec", false },
  { "exec", false },
  { "exec", false }
  };
  return kImplicitRegRefs;
}

const std::vector<GcnGeneratedOperandSpec>& GeneratedGcnOperandSpecs() {
  static const std::vector<GcnGeneratedOperandSpec> kOperandSpecs = {
  { "sdst", "scalar_reg", "def", "sdst", 1, 1, "" },
  { "sbase", "scalar_reg_range", "use", "sbase", 2, 2, "" },
  { "offset", "immediate_field", "use", "offset", 1, 1, "" },
  { "sdst", "scalar_reg_range", "def", "sdst", 2, 1, "" },
  { "sbase", "scalar_reg_range", "use", "sbase", 2, 2, "" },
  { "offset", "immediate_field", "use", "offset", 1, 1, "" },
  { "sdst", "scalar_reg_range", "def", "sdst", 4, 1, "" },
  { "sbase", "scalar_reg_range", "use", "sbase", 2, 2, "" },
  { "offset", "immediate_field", "use", "offset", 1, 1, "" },
  { "sdst", "scalar_reg", "def", "sdst", 1, 1, "" },
  { "src0", "scalar_src8", "use", "ssrc0", 1, 1, "" },
  { "src1", "scalar_src8", "use", "ssrc1", 1, 1, "" },
  { "sdst", "scalar_reg", "def", "sdst", 1, 1, "" },
  { "src0", "scalar_src8", "use", "ssrc0", 1, 1, "" },
  { "src1", "scalar_src8", "use", "ssrc1", 1, 1, "" },
  { "vdst", "vector_reg", "def", "vdst", 1, 1, "" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "vsrc1", "vector_reg", "use", "vsrc1", 1, 1, "" },
  { "vcc", "special_reg", "def", "", 1, 1, "vcc" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "vsrc1", "vector_reg", "use", "vsrc1", 1, 1, "" },
  { "dst", "scalar_reg_pair_dest", "def", "sdst", 1, 1, "" },
  { "src0", "scalar_src8_pair", "use", "ssrc0", 1, 1, "" },
  { "target", "branch_target", "use", "simm16", 1, 1, "" },
  { "vdst", "vector_reg", "def", "vdst", 1, 1, "" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "vsrc1", "vector_reg", "use", "vsrc1", 1, 1, "" },
  { "waitcnt", "waitcnt_fields", "use", "simm16", 1, 1, "" },
  { "vdst", "vector_reg", "def", "vdst", 1, 1, "" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "vdst", "vector_reg", "def", "vdst", 1, 1, "" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "vsrc1", "vector_reg", "use", "vsrc1", 1, 1, "" },
  { "vdst", "vector_reg", "def", "vdst", 1, 1, "" },
  { "vcc", "special_reg", "def", "", 1, 1, "vcc" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "vsrc1", "vector_reg", "use", "vsrc1", 1, 1, "" },
  { "vdst", "vector_reg", "def", "vdst", 1, 1, "" },
  { "vcc_dst", "special_reg", "def", "", 1, 1, "vcc" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "vsrc1", "vector_reg", "use", "vsrc1", 1, 1, "" },
  { "vcc_src", "special_reg", "use", "", 1, 1, "vcc" },
  { "vdst", "vector_reg_range_field", "def", "vdst", 2, 1, "" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "src1", "src9_or_vector_reg_range2", "use", "src1", 2, 1, "" },
  { "vdst", "vector_reg", "def", "vdst", 1, 1, "" },
  { "addr", "flat_addr", "use", "addr", 1, 1, "" },
  { "offset", "flat_offset13", "use", "offset", 1, 1, "" },
  { "addr", "flat_addr", "use", "addr", 1, 1, "" },
  { "data", "vector_reg", "use", "data", 1, 1, "" },
  { "offset", "flat_offset13", "use", "offset", 1, 1, "" },
  { "sdst", "scalar_reg", "def", "sdst", 1, 1, "" },
  { "src0", "scalar_src8", "use", "ssrc0", 1, 1, "" },
  { "literal", "immediate_literal32", "use", "", 1, 1, "" },
  { "src0", "scalar_src8", "use", "ssrc0", 1, 1, "" },
  { "src1", "scalar_src8", "use", "ssrc1", 1, 1, "" },
  { "target", "branch_target", "use", "simm16", 1, 1, "" },
  { "sdst", "scalar_reg", "def", "sdst", 1, 1, "" },
  { "src0", "scalar_src8", "use", "ssrc0", 1, 1, "" },
  { "src1", "scalar_src8", "use", "ssrc1", 1, 1, "" },
  { "src0", "scalar_src8", "use", "ssrc0", 1, 1, "" },
  { "src1", "scalar_src8", "use", "ssrc1", 1, 1, "" },
  { "vdst", "vector_reg", "def", "vdst", 1, 1, "" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "src1", "src9", "use", "src1", 1, 1, "" },
  { "src2", "src9", "use", "src2", 1, 1, "" },
  { "target", "branch_target", "use", "simm16", 1, 1, "" },
  { "target", "branch_target", "use", "simm16", 1, 1, "" },
  { "sdst", "scalar_reg_range", "def", "sdst", 2, 1, "" },
  { "src0", "scalar_src8", "use", "ssrc0", 1, 1, "" },
  { "src1", "scalar_src8", "use", "ssrc1", 1, 1, "" },
  { "barrier", "special_reg", "use", "", 1, 1, "barrier" },
  { "addr", "vector_reg", "use", "addr", 1, 1, "" },
  { "data0", "vector_reg", "use", "data0", 1, 1, "" },
  { "vdst", "vector_reg", "def", "vdst", 1, 1, "" },
  { "addr", "vector_reg", "use", "addr", 1, 1, "" },
  { "vdst", "vector_reg", "def", "vdst", 1, 1, "" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "vdst", "vector_reg", "def", "vdst", 1, 1, "" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "vsrc1", "vector_reg", "use", "vsrc1", 1, 1, "" },
  { "vdst", "vector_reg", "def", "vdst", 1, 1, "" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "src1", "src9", "use", "src1", 1, 1, "" },
  { "src2", "src9", "use", "src2", 1, 1, "" },
  { "vdst", "vector_reg", "def", "vdst", 1, 1, "" },
  { "sdst", "vop3_sdst_pair", "def", "", 2, 1, "" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "src1", "src9", "use", "src1", 1, 1, "" },
  { "vdst", "vector_reg", "def", "vdst", 1, 1, "" },
  { "sdst", "vop3_sdst_pair", "def", "", 2, 1, "" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "src1", "src9", "use", "src1", 1, 1, "" },
  { "src2", "vop3_src2_pair", "use", "src2", 2, 1, "" },
  { "vdst", "vector_reg", "def", "vdst", 1, 1, "" },
  { "literal", "immediate_literal32", "use", "", 1, 1, "" },
  { "sdst", "vop3_sdst_pair", "def", "", 2, 1, "" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "src1", "src9", "use", "src1", 1, 1, "" },
  { "src0", "scalar_src8", "use", "ssrc0", 1, 1, "" },
  { "src1", "scalar_src8", "use", "ssrc1", 1, 1, "" },
  { "src0", "scalar_src8", "use", "ssrc0", 1, 1, "" },
  { "src1", "scalar_src8", "use", "ssrc1", 1, 1, "" },
  { "sdst", "scalar_reg_range", "def", "sdst", 2, 1, "" },
  { "src0", "scalar_src8", "use", "ssrc0", 1, 1, "" },
  { "src1", "scalar_src8", "use", "ssrc1", 1, 1, "" },
  { "dst", "scalar_reg_pair_dest", "def", "sdst", 2, 1, "" },
  { "src0", "scalar_src8", "use", "ssrc0", 1, 1, "" },
  { "src1", "scalar_src8_pair", "use", "ssrc1", 2, 1, "" },
  { "target", "branch_target", "use", "simm16", 1, 1, "" },
  { "vdst", "vector_reg", "def", "vdst", 1, 1, "" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "vsrc1", "vector_reg", "use", "vsrc1", 1, 1, "" },
  { "vdst", "vector_reg", "def", "vdst", 1, 1, "" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "vsrc1", "vector_reg", "use", "vsrc1", 1, 1, "" },
  { "vdst", "vector_reg", "def", "vdst", 1, 1, "" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "vsrc1", "vector_reg", "use", "vsrc1", 1, 1, "" },
  { "vdst", "vector_reg", "def", "vdst", 1, 1, "" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "vsrc1", "vector_reg", "use", "vsrc1", 1, 1, "" },
  { "vdst", "vector_reg", "def", "vdst", 1, 1, "" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "vsrc1", "vector_reg", "use", "vsrc1", 1, 1, "" },
  { "vdst", "vector_reg", "def", "vdst", 1, 1, "" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "vdst", "vector_reg", "def", "vdst", 1, 1, "" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "vdst", "vector_reg", "def", "vdst", 1, 1, "" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "vdst", "vector_reg", "def", "vdst", 1, 1, "" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "sdst", "scalar_reg", "def", "sdst", 1, 1, "" },
  { "src0", "scalar_src8", "use", "ssrc0", 1, 1, "" },
  { "sdst", "scalar_reg", "def", "sdst", 1, 1, "" },
  { "literal", "immediate_literal32", "use", "", 1, 1, "" },
  { "sdst", "scalar_reg", "def", "sdst", 1, 1, "" },
  { "src0", "scalar_src8", "use", "ssrc0", 1, 1, "" },
  { "src1", "scalar_src8", "use", "ssrc1", 1, 1, "" },
  { "vcc", "special_reg", "def", "", 1, 1, "vcc" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "vsrc1", "vector_reg", "use", "vsrc1", 1, 1, "" },
  { "vcc", "special_reg", "def", "", 1, 1, "vcc" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "vsrc1", "vector_reg", "use", "vsrc1", 1, 1, "" },
  { "vcc", "special_reg", "def", "", 1, 1, "vcc" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "vsrc1", "vector_reg", "use", "vsrc1", 1, 1, "" },
  { "vdst", "vector_reg", "def", "vdst", 1, 1, "" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "src1", "src9", "use", "src1", 1, 1, "" },
  { "src2", "vop3_src2_pair", "use", "src2", 2, 1, "" },
  { "vdst", "vector_reg", "def", "vdst", 1, 1, "" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "src1", "src9", "use", "src1", 1, 1, "" },
  { "src2", "src9", "use", "src2", 1, 1, "" },
  { "vdst", "vector_reg", "def", "vdst", 1, 1, "" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "src1", "src9", "use", "src1", 1, 1, "" },
  { "src2", "src9", "use", "src2", 1, 1, "" },
  { "vdst", "vector_reg", "def", "vdst", 1, 1, "" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "src1", "src9", "use", "src1", 1, 1, "" },
  { "src2", "src9", "use", "src2", 1, 1, "" },
  { "vdst", "vector_reg", "def", "vdst", 1, 1, "" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "src1", "src9", "use", "src1", 1, 1, "" },
  { "src2", "src9", "use", "src2", 1, 1, "" },
  { "vdst", "vector_reg", "def", "vdst", 1, 1, "" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "vsrc1", "vector_reg", "use", "vsrc1", 1, 1, "" },
  { "vdst", "vector_reg", "def", "vdst", 1, 1, "" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "vsrc1", "vector_reg", "use", "vsrc1", 1, 1, "" },
  { "vcc", "special_reg", "def", "", 1, 1, "vcc" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "vsrc1", "vector_reg", "use", "vsrc1", 1, 1, "" },
  { "vdst", "vector_reg", "def", "vdst", 1, 1, "" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "src1", "src9", "use", "src1", 1, 1, "" },
  { "src2", "src9", "use", "src2", 1, 1, "" },
  { "vdst", "vector_reg", "def", "vdst", 1, 1, "" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "src1", "src9", "use", "src1", 1, 1, "" },
  { "src2", "src9", "use", "src2", 1, 1, "" },
  { "vdst", "vector_reg", "def", "vdst", 1, 1, "" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "src1", "src9", "use", "src1", 1, 1, "" },
  { "src2", "src9", "use", "src2", 1, 1, "" },
  { "vdst", "vector_reg", "def", "vdst", 1, 1, "" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "src1", "src9", "use", "src1", 1, 1, "" },
  { "src2", "src9", "use", "src2", 1, 1, "" },
  { "vdst", "vector_reg", "def", "vdst", 1, 1, "" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "src1", "src9", "use", "src1", 1, 1, "" },
  { "src2", "src9", "use", "src2", 1, 1, "" },
  { "vdst", "vector_reg", "def", "vdst", 1, 1, "" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "src1", "src9", "use", "src1", 1, 1, "" },
  { "src2", "src9", "use", "src2", 1, 1, "" },
  { "vdst", "vector_reg", "def", "vdst", 1, 1, "" },
  { "src0", "accumulator_reg", "use", "src0", 1, 1, "" },
  { "vdst", "accumulator_reg", "def", "vdst", 1, 1, "" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "sdst", "scalar_reg", "def", "sdst", 1, 1, "" },
  { "src0", "scalar_src8", "use", "ssrc0", 1, 1, "" },
  { "src1", "scalar_src8", "use", "ssrc1", 1, 1, "" },
  { "sdst", "scalar_reg", "def", "sdst", 1, 1, "" },
  { "src0", "scalar_src8", "use", "ssrc0", 1, 1, "" },
  { "src1", "scalar_src8", "use", "ssrc1", 1, 1, "" },
  { "dst", "scalar_reg_pair_dest", "def", "sdst", 1, 1, "" },
  { "src0", "scalar_src8_pair", "use", "ssrc0", 1, 1, "" },
  { "sdst", "scalar_reg", "def", "sdst", 1, 1, "" },
  { "src0", "scalar_src8", "use", "ssrc0", 1, 1, "" },
  { "src1", "scalar_src8", "use", "ssrc1", 1, 1, "" },
  { "sdst", "scalar_reg_range", "def", "sdst", 2, 1, "" },
  { "src0", "scalar_src8_pair", "use", "ssrc0", 2, 1, "" },
  { "src1", "scalar_src8", "use", "ssrc1", 1, 1, "" },
  { "target", "branch_target", "use", "simm16", 1, 1, "" },
  { "vcc", "special_reg", "def", "", 1, 1, "vcc" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "vsrc1", "vector_reg", "use", "vsrc1", 1, 1, "" },
  { "vcc", "special_reg", "def", "", 1, 1, "vcc" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "vsrc1", "vector_reg", "use", "vsrc1", 1, 1, "" },
  { "dst", "scalar_reg_pair_dest", "def", "sdst", 1, 1, "" },
  { "src0", "scalar_src8", "use", "ssrc0", 1, 1, "" },
  { "src1", "scalar_src8_pair", "use", "ssrc1", 1, 1, "" },
  { "sdst", "scalar_reg", "def", "sdst", 1, 1, "" },
  { "simm16", "simm16", "use", "simm16", 1, 1, "" },
  { "vdst", "vector_reg_range_field", "def", "vdst", 2, 1, "" },
  { "sdst", "vop3_sdst_pair", "def", "", 2, 1, "" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "src1", "src9", "use", "src1", 1, 1, "" },
  { "src2", "src9_or_vector_reg_range2", "use", "src2", 2, 1, "" },
  { "vdst", "vector_reg", "def", "vdst", 1, 1, "" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "vdst", "vector_reg", "def", "vdst", 1, 1, "" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "src1", "src9", "use", "src1", 1, 1, "" },
  { "vdst", "vector_reg", "def", "vdst", 1, 1, "" },
  { "src0", "src9", "use", "src0", 1, 1, "" },
  { "src1", "src9", "use", "src1", 1, 1, "" },
  { "sdst", "scalar_reg", "def", "sdst", 1, 1, "" },
  { "src0", "scalar_src8_pair", "use", "ssrc0", 1, 1, "" },
  { "vdst", "vector_reg", "def", "addr", 1, 1, "" },
  { "data", "vector_reg", "use", "data", 1, 1, "" },
  { "saddr", "scalar_reg_range", "use", "saddr", 2, 1, "" }
  };
  return kOperandSpecs;
}

const std::vector<GcnGeneratedFieldRef>& GeneratedGcnFieldRefs() {
  static const std::vector<GcnGeneratedFieldRef> kFieldRefs = {
  { "ssrc0", 0, 0, 8, false, "scalar source 0 selector" },
  { "ssrc1", 0, 8, 8, false, "scalar source 1 selector" },
  { "sdst", 0, 16, 7, false, "scalar destination register" },
  { "op", 0, 23, 7, false, "opcode selector" },
  { "enc", 0, 30, 2, false, "format encoding tag" },
  { "simm16", 0, 0, 16, true, "16-bit signed immediate" },
  { "sdst", 0, 16, 7, false, "scalar destination register" },
  { "op", 0, 23, 5, false, "opcode selector" },
  { "enc", 0, 28, 4, false, "format encoding tag" },
  { "ssrc0", 0, 0, 8, false, "scalar source selector or inline literal marker" },
  { "op", 0, 8, 8, false, "opcode selector" },
  { "sdst", 0, 16, 7, false, "scalar destination register" },
  { "enc", 0, 23, 9, false, "format encoding tag" },
  { "ssrc0", 0, 0, 8, false, "scalar source 0 selector" },
  { "ssrc1", 0, 8, 8, false, "scalar source 1 selector" },
  { "op", 0, 16, 7, false, "opcode selector" },
  { "enc", 0, 23, 9, false, "format encoding tag" },
  { "simm16", 0, 0, 16, true, "branch/control immediate" },
  { "op", 0, 16, 7, false, "opcode selector" },
  { "enc", 0, 23, 9, false, "format encoding tag" },
  { "offset", 0, 0, 8, false, "scalar memory offset or immediate field" },
  { "imm", 0, 8, 1, false, "offset immediate selector" },
  { "sbase", 0, 9, 6, false, "scalar base register pair selector" },
  { "sdst", 0, 15, 7, false, "scalar destination register or range base" },
  { "op_lo", 0, 22, 5, false, "opcode low bits" },
  { "op_hi", 0, 18, 2, false, "opcode high bits" },
  { "enc", 0, 27, 5, false, "format encoding tag" },
  { "src0", 0, 0, 9, false, "source 0 selector" },
  { "vsrc1", 0, 9, 8, false, "vector source 1 register" },
  { "vdst", 0, 17, 8, false, "vector destination register" },
  { "op", 0, 25, 6, false, "opcode selector" },
  { "enc", 0, 31, 1, false, "format encoding tag" },
  { "src0", 0, 0, 9, false, "source 0 selector" },
  { "op", 0, 9, 8, false, "opcode selector" },
  { "vdst", 0, 17, 8, false, "vector destination register" },
  { "enc", 0, 25, 7, false, "format encoding tag" },
  { "src0", 0, 0, 9, false, "source 0 selector" },
  { "vsrc1", 0, 9, 8, false, "vector source 1 register" },
  { "op", 0, 17, 8, false, "opcode selector" },
  { "enc", 0, 25, 7, false, "format encoding tag" },
  { "vdst", 0, 0, 8, false, "vector destination register" },
  { "abs", 0, 8, 3, false, "per-source abs modifiers" },
  { "clamp", 0, 11, 1, false, "result clamp modifier" },
  { "op", 0, 17, 9, false, "opcode selector" },
  { "enc", 0, 26, 6, false, "format encoding tag" },
  { "src0", 1, 0, 9, false, "source 0 selector" },
  { "src1", 1, 9, 9, false, "source 1 selector" },
  { "src2", 1, 18, 9, false, "source 2 selector" },
  { "omod", 1, 27, 2, false, "output modifier" },
  { "neg", 1, 29, 3, false, "per-source neg modifiers" },
  { "vdst", 0, 0, 8, false, "vector destination register" },
  { "op", 0, 16, 7, false, "opcode selector" },
  { "enc", 0, 23, 9, false, "format encoding tag" },
  { "src0", 1, 0, 9, false, "source 0 selector" },
  { "src1", 1, 9, 9, false, "source 1 selector" },
  { "src2", 1, 18, 9, false, "source 2 selector" },
  { "op_sel_hi", 1, 27, 2, false, "high op_sel bits / variant modifiers" },
  { "neg_lo", 1, 29, 3, false, "negation / variant modifier bits" },
  { "offset0", 0, 0, 8, false, "LDS offset 0" },
  { "offset1", 0, 8, 8, false, "LDS offset 1" },
  { "gds", 0, 16, 1, false, "GDS selector bit" },
  { "op", 0, 17, 8, false, "opcode selector" },
  { "enc", 0, 26, 6, false, "format encoding tag" },
  { "addr", 1, 0, 8, false, "address VGPR" },
  { "data0", 1, 8, 8, false, "data source 0 VGPR" },
  { "data1", 1, 16, 8, false, "data source 1 VGPR" },
  { "vdst", 1, 24, 8, false, "destination VGPR" },
  { "offset", 0, 0, 13, false, "flat/global offset" },
  { "lds", 0, 13, 1, false, "LDS path selector" },
  { "seg", 0, 14, 2, false, "segment selector" },
  { "glc", 0, 16, 1, false, "global coherency bit" },
  { "slc", 0, 17, 1, false, "system level coherency bit" },
  { "op", 0, 18, 7, false, "opcode selector" },
  { "enc", 0, 25, 6, false, "format encoding tag" },
  { "addr", 1, 0, 8, false, "address VGPR base" },
  { "data", 1, 8, 8, false, "data VGPR or source" },
  { "saddr", 1, 16, 7, false, "scalar address register selector" },
  { "nv", 1, 23, 1, false, "address component count flag" },
  { "vdst", 1, 24, 8, false, "destination VGPR" }
  };
  return kFieldRefs;
}

const std::vector<GcnGeneratedFormatDef>& GeneratedGcnFormatDefs() {
  static const std::vector<GcnGeneratedFormatDef> kFormatDefs = {
  { "sop2", EncodedGcnInstFormatClass::Sop2, 4, { "op", 0, 23, 7, false, "scalar SOP2 opcode" }, 0, 5 },
  { "sopk", EncodedGcnInstFormatClass::Sopk, 4, { "op", 0, 23, 5, false, "scalar SOPK opcode" }, 5, 4 },
  { "sop1", EncodedGcnInstFormatClass::Sop1, 4, { "op", 0, 8, 8, false, "scalar SOP1 opcode" }, 9, 4 },
  { "sopc", EncodedGcnInstFormatClass::Sopc, 4, { "op", 0, 16, 7, false, "scalar compare opcode" }, 13, 4 },
  { "sopp", EncodedGcnInstFormatClass::Sopp, 4, { "op", 0, 16, 7, false, "scalar branch/control opcode" }, 17, 3 },
  { "smrd", EncodedGcnInstFormatClass::Smrd, 8, { "op", 0, 22, 7, false, "scalar memory opcode (split field normalized)" }, 20, 7 },
  { "vop2", EncodedGcnInstFormatClass::Vop2, 4, { "op", 0, 25, 6, false, "vector VOP2 opcode" }, 27, 5 },
  { "vop1", EncodedGcnInstFormatClass::Vop1, 4, { "op", 0, 9, 8, false, "vector VOP1 opcode" }, 32, 4 },
  { "vopc", EncodedGcnInstFormatClass::Vopc, 4, { "op", 0, 17, 8, false, "vector compare opcode" }, 36, 4 },
  { "vop3a", EncodedGcnInstFormatClass::Vop3a, 8, { "op", 0, 17, 9, false, "vector VOP3A opcode" }, 40, 10 },
  { "vop3p", EncodedGcnInstFormatClass::Vop3p, 8, { "op", 0, 16, 7, false, "vector VOP3P opcode" }, 50, 8 },
  { "ds", EncodedGcnInstFormatClass::Ds, 8, { "op", 0, 17, 8, false, "DS/LDS opcode" }, 58, 9 },
  { "flat", EncodedGcnInstFormatClass::Flat, 8, { "op", 0, 18, 7, false, "FLAT/GLOBAL opcode" }, 67, 12 }
  };
  return kFormatDefs;
}

const std::vector<GcnGeneratedInstDef>& GeneratedGcnInstDefs() {
  static const std::vector<GcnGeneratedInstDef> kInstDefs = {
  { 1, "gfx6_gfx8", EncodedGcnInstFormatClass::Sopp, 1, 4, "s_endpgm", "sync", "branch_or_sync", "branch_or_special", kGcnInstFlagIsBranch, 0, 0, 0, 0 },
  { 2, "gfx6_gfx8", EncodedGcnInstFormatClass::Smrd, 0, 8, "s_load_dword", "memory", "scalar_memory", "scalar_alu_or_memory", kGcnInstFlagIsMemory, 0, 0, 0, 3 },
  { 3, "gfx6_gfx8", EncodedGcnInstFormatClass::Smrd, 32, 8, "s_load_dwordx2", "memory", "scalar_memory", "scalar_alu_or_memory", kGcnInstFlagIsMemory, 0, 0, 3, 3 },
  { 4, "gfx6_gfx8", EncodedGcnInstFormatClass::Smrd, 64, 8, "s_load_dwordx4", "memory", "scalar_memory", "scalar_alu_or_memory", kGcnInstFlagIsMemory, 0, 0, 6, 3 },
  { 5, "gfx6_gfx8", EncodedGcnInstFormatClass::Sop2, 12, 4, "s_and_b32", "compute", "scalar_alu", "scalar_alu_or_memory", kGcnInstFlagNone, 0, 0, 9, 3 },
  { 6, "gfx6_gfx8", EncodedGcnInstFormatClass::Sop2, 36, 4, "s_mul_i32", "compute", "scalar_alu", "scalar_alu_or_memory", kGcnInstFlagNone, 0, 0, 12, 3 },
  { 7, "gfx6_gfx8", EncodedGcnInstFormatClass::Vop2, 52, 4, "v_add_u32_e32", "compute", "vector_alu", "vector_alu", kGcnInstFlagNone, 0, 0, 15, 3 },
  { 8, "gfx6_gfx8", EncodedGcnInstFormatClass::Vopc, 196, 4, "v_cmp_gt_i32_e32", "control", "vector_compare", "vector_alu", kGcnInstFlagWritesVcc, 0, 0, 18, 3 },
  { 9, "gfx6_gfx8", EncodedGcnInstFormatClass::Sop1, 32, 4, "s_and_saveexec_b64", "compute", "scalar_alu", "scalar_alu_or_memory", kGcnInstFlagWritesExec, 0, 0, 21, 2 },
  { 10, "gfx6_gfx8", EncodedGcnInstFormatClass::Sopp, 8, 4, "s_cbranch_execz", "sync", "branch_or_sync", "branch_or_special", kGcnInstFlagIsBranch, 0, 1, 23, 1 },
  { 11, "gfx6_gfx8", EncodedGcnInstFormatClass::Vop2, 1, 4, "v_add_f32_e32", "compute", "vector_alu", "vector_alu", kGcnInstFlagNone, 1, 0, 24, 3 },
  { 12, "gfx6_gfx8", EncodedGcnInstFormatClass::Sopp, 12, 4, "s_waitcnt", "sync", "branch_or_sync", "branch_or_special", kGcnInstFlagIsWaitcnt, 1, 0, 27, 1 },
  { 13, "gfx6_gfx8", EncodedGcnInstFormatClass::Vop1, 1, 4, "v_mov_b32_e32", "compute", "vector_alu", "vector_alu", kGcnInstFlagNone, 1, 0, 28, 2 },
  { 14, "gfx6_gfx8", EncodedGcnInstFormatClass::Vop2, 17, 4, "v_ashrrev_i32_e32", "compute", "vector_alu", "vector_alu", kGcnInstFlagNone, 1, 0, 30, 3 },
  { 15, "gfx6_gfx8", EncodedGcnInstFormatClass::Vop2, 25, 4, "v_add_co_u32_e32", "compute", "vector_alu", "vector_alu", kGcnInstFlagNone, 1, 0, 33, 4 },
  { 16, "gfx6_gfx8", EncodedGcnInstFormatClass::Vop2, 28, 4, "v_addc_co_u32_e32", "compute", "vector_alu", "vector_alu", kGcnInstFlagNone, 1, 0, 37, 5 },
  { 17, "gfx6_gfx8", EncodedGcnInstFormatClass::Vop3a, 327, 8, "v_lshlrev_b64", "compute", "vector_alu", "vector_alu", kGcnInstFlagNone, 1, 0, 42, 3 },
  { 18, "gfx6_gfx8", EncodedGcnInstFormatClass::Flat, 20, 8, "global_load_dword", "memory", "vector_memory", "vector_memory", kGcnInstFlagIsMemory, 1, 1, 45, 3 },
  { 19, "gfx6_gfx8", EncodedGcnInstFormatClass::Flat, 28, 8, "global_store_dword", "memory", "vector_memory", "vector_memory", kGcnInstFlagIsMemory, 2, 1, 48, 3 },
  { 20, "gfx6_gfx8", EncodedGcnInstFormatClass::Sop2, 12, 8, "s_and_b32", "compute", "scalar_alu", "scalar_alu_or_memory", kGcnInstFlagNone, 3, 0, 51, 3 },
  { 21, "gfx6_gfx8", EncodedGcnInstFormatClass::Sopc, 4, 4, "s_cmp_lt_i32", "control", "scalar_compare", "scalar_alu_or_memory", kGcnInstFlagNone, 3, 0, 54, 2 },
  { 22, "gfx6_gfx8", EncodedGcnInstFormatClass::Sopp, 5, 4, "s_cbranch_scc1", "sync", "branch_or_sync", "branch_or_special", kGcnInstFlagIsBranch, 3, 1, 56, 1 },
  { 23, "gfx6_gfx8", EncodedGcnInstFormatClass::Sop2, 2, 4, "s_add_i32", "compute", "scalar_alu", "scalar_alu_or_memory", kGcnInstFlagNone, 4, 0, 57, 3 },
  { 24, "gfx6_gfx8", EncodedGcnInstFormatClass::Sopc, 6, 4, "s_cmp_eq_u32", "control", "scalar_compare", "scalar_alu_or_memory", kGcnInstFlagWritesScc, 4, 0, 60, 2 },
  { 25, "gfx6_gfx8", EncodedGcnInstFormatClass::Vop3a, 229, 8, "v_fma_f32", "compute", "vector_alu", "vector_alu", kGcnInstFlagNone, 4, 0, 62, 4 },
  { 26, "gfx6_gfx8", EncodedGcnInstFormatClass::Sopp, 4, 4, "s_cbranch_scc0", "sync", "branch_or_sync", "branch_or_special", kGcnInstFlagIsBranch, 4, 1, 66, 1 },
  { 27, "gfx6_gfx8", EncodedGcnInstFormatClass::Sopp, 2, 4, "s_branch", "sync", "branch_or_sync", "branch_or_special", kGcnInstFlagIsBranch, 5, 0, 67, 1 },
  { 28, "gfx6_gfx8", EncodedGcnInstFormatClass::Sop2, 15, 4, "s_or_b64", "compute", "scalar_alu", "scalar_alu_or_memory", kGcnInstFlagNone, 5, 0, 68, 3 },
  { 29, "gfx6_gfx8", EncodedGcnInstFormatClass::Sopp, 10, 4, "s_barrier", "sync", "branch_or_sync", "branch_or_special", kGcnInstFlagIsBarrier, 5, 0, 71, 1 },
  { 30, "gfx6_gfx8", EncodedGcnInstFormatClass::Ds, 13, 8, "ds_write_b32", "memory", "lds", "lds", kGcnInstFlagIsMemory, 5, 1, 72, 2 },
  { 31, "gfx6_gfx8", EncodedGcnInstFormatClass::Ds, 54, 8, "ds_read_b32", "memory", "lds", "lds", kGcnInstFlagIsMemory, 6, 1, 74, 2 },
  { 32, "gfx6_gfx8", EncodedGcnInstFormatClass::Vop1, 43, 4, "v_not_b32_e32", "compute", "vector_alu", "vector_alu", kGcnInstFlagNone, 7, 0, 76, 2 },
  { 33, "gfx6_gfx8", EncodedGcnInstFormatClass::Vop2, 18, 4, "v_lshlrev_b32_e32", "compute", "vector_alu", "vector_alu", kGcnInstFlagNone, 7, 0, 78, 3 },
  { 34, "gfx6_gfx8", EncodedGcnInstFormatClass::Vop3a, 254, 8, "v_lshl_add_u32", "compute", "vector_alu", "vector_alu", kGcnInstFlagNone, 7, 0, 81, 4 },
  { 35, "gfx6_gfx8", EncodedGcnInstFormatClass::Vop3a, 140, 8, "v_add_co_u32_e64", "compute", "vector_alu", "vector_alu", kGcnInstFlagNone, 7, 0, 85, 4 },
  { 36, "gfx6_gfx8", EncodedGcnInstFormatClass::Vop3a, 142, 8, "v_addc_co_u32_e64", "compute", "vector_alu", "vector_alu", kGcnInstFlagNone, 7, 0, 89, 5 },
  { 37, "gfx6_gfx8", EncodedGcnInstFormatClass::Vop1, 1, 8, "v_mov_b32_e32", "compute", "vector_alu", "vector_alu", kGcnInstFlagNone, 7, 0, 94, 2 },
  { 38, "gfx6_gfx8", EncodedGcnInstFormatClass::Vop3a, 98, 8, "v_cmp_gt_i32_e64", "compute", "vector_alu", "vector_alu", kGcnInstFlagNone, 7, 0, 96, 3 },
  { 39, "gfx6_gfx8", EncodedGcnInstFormatClass::Sopc, 8, 4, "s_cmp_gt_u32", "control", "scalar_compare", "scalar_alu_or_memory", kGcnInstFlagNone, 7, 0, 99, 2 },
  { 40, "gfx6_gfx8", EncodedGcnInstFormatClass::Sopc, 10, 4, "s_cmp_lt_u32", "control", "scalar_compare", "scalar_alu_or_memory", kGcnInstFlagNone, 7, 0, 101, 2 },
  { 41, "gfx6_gfx8", EncodedGcnInstFormatClass::Sop2, 11, 4, "s_cselect_b64", "compute", "scalar_alu", "scalar_alu_or_memory", kGcnInstFlagNone, 7, 0, 103, 3 },
  { 42, "gfx6_gfx8", EncodedGcnInstFormatClass::Sop2, 19, 4, "s_andn2_b64", "compute", "scalar_alu", "scalar_alu_or_memory", kGcnInstFlagNone, 7, 0, 106, 3 },
  { 43, "gfx6_gfx8", EncodedGcnInstFormatClass::Sopp, 6, 4, "s_cbranch_vccz", "sync", "branch_or_sync", "branch_or_special", kGcnInstFlagNone, 7, 0, 109, 1 },
  { 44, "gfx6_gfx8", EncodedGcnInstFormatClass::Vop2, 2, 4, "v_sub_f32_e32", "compute", "vector_alu", "vector_alu", kGcnInstFlagNone, 7, 0, 110, 3 },
  { 45, "gfx6_gfx8", EncodedGcnInstFormatClass::Vop2, 5, 8, "v_mul_f32_e32", "compute", "vector_alu", "vector_alu", kGcnInstFlagNone, 7, 0, 113, 3 },
  { 46, "gfx6_gfx8", EncodedGcnInstFormatClass::Vop2, 11, 4, "v_max_f32_e32", "compute", "vector_alu", "vector_alu", kGcnInstFlagNone, 7, 0, 116, 3 },
  { 47, "gfx6_gfx8", EncodedGcnInstFormatClass::Vop2, 59, 8, "v_fmac_f32_e32", "compute", "vector_alu", "vector_alu", kGcnInstFlagNone, 7, 0, 119, 3 },
  { 48, "gfx6_gfx8", EncodedGcnInstFormatClass::Vop2, 0, 4, "v_cndmask_b32_e32", "compute", "vector_alu", "vector_alu", kGcnInstFlagNone, 7, 0, 122, 3 },
  { 49, "gfx6_gfx8", EncodedGcnInstFormatClass::Vop1, 8, 4, "v_cvt_i32_f32_e32", "compute", "vector_alu", "vector_alu", kGcnInstFlagNone, 7, 0, 125, 2 },
  { 50, "gfx6_gfx8", EncodedGcnInstFormatClass::Vop1, 30, 4, "v_rndne_f32_e32", "compute", "vector_alu", "vector_alu", kGcnInstFlagNone, 7, 0, 127, 2 },
  { 51, "gfx6_gfx8", EncodedGcnInstFormatClass::Vop1, 32, 4, "v_exp_f32_e32", "compute", "vector_alu", "vector_alu", kGcnInstFlagNone, 7, 0, 129, 2 },
  { 52, "gfx6_gfx8", EncodedGcnInstFormatClass::Vop1, 34, 4, "v_rcp_f32_e32", "compute", "vector_alu", "vector_alu", kGcnInstFlagNone, 7, 0, 131, 2 },
  { 53, "gfx6_gfx8", EncodedGcnInstFormatClass::Sop1, 0, 4, "s_mov_b32", "compute", "scalar_alu", "scalar_alu_or_memory", kGcnInstFlagNone, 7, 0, 133, 2 },
  { 54, "gfx6_gfx8", EncodedGcnInstFormatClass::Sop1, 0, 8, "s_mov_b32", "compute", "scalar_alu", "scalar_alu_or_memory", kGcnInstFlagNone, 7, 0, 135, 2 },
  { 55, "gfx6_gfx8", EncodedGcnInstFormatClass::Sop2, 30, 4, "s_lshr_b32", "compute", "scalar_alu", "scalar_alu_or_memory", kGcnInstFlagNone, 7, 0, 137, 3 },
  { 56, "gfx6_gfx8", EncodedGcnInstFormatClass::Vopc, 204, 4, "v_cmp_gt_u32_e32", "control", "vector_compare", "vector_alu", kGcnInstFlagNone, 7, 0, 140, 3 },
  { 57, "gfx6_gfx8", EncodedGcnInstFormatClass::Vopc, 75, 4, "v_cmp_ngt_f32_e32", "control", "vector_compare", "vector_alu", kGcnInstFlagNone, 7, 0, 143, 3 },
  { 58, "gfx6_gfx8", EncodedGcnInstFormatClass::Vopc, 78, 4, "v_cmp_nlt_f32_e32", "control", "vector_compare", "vector_alu", kGcnInstFlagNone, 7, 0, 146, 3 },
  { 59, "gfx6_gfx8", EncodedGcnInstFormatClass::Vop3a, 128, 8, "v_cndmask_b32_e64", "compute", "vector_alu", "vector_alu", kGcnInstFlagNone, 7, 0, 149, 4 },
  { 60, "gfx6_gfx8", EncodedGcnInstFormatClass::Vop3a, 239, 8, "v_div_fixup_f32", "compute", "vector_alu", "vector_alu", kGcnInstFlagNone, 7, 0, 153, 4 },
  { 61, "gfx6_gfx8", EncodedGcnInstFormatClass::Vop3a, 240, 8, "v_div_scale_f32", "compute", "vector_alu", "vector_alu", kGcnInstFlagNone, 7, 0, 157, 4 },
  { 62, "gfx6_gfx8", EncodedGcnInstFormatClass::Vop3a, 241, 8, "v_div_fmas_f32", "compute", "vector_alu", "vector_alu", kGcnInstFlagNone, 7, 0, 161, 4 },
  { 63, "gfx6_gfx8", EncodedGcnInstFormatClass::Vop3a, 324, 8, "v_ldexp_f32", "compute", "vector_alu", "vector_alu", kGcnInstFlagNone, 7, 0, 165, 4 },
  { 64, "gfx6_gfx8", EncodedGcnInstFormatClass::Vop2, 5, 4, "v_mul_f32_e32", "compute", "vector_alu", "vector_alu", kGcnInstFlagNone, 7, 0, 169, 3 },
  { 65, "gfx6_gfx8", EncodedGcnInstFormatClass::Vop2, 59, 4, "v_fmac_f32_e32", "compute", "vector_alu", "vector_alu", kGcnInstFlagNone, 7, 0, 172, 3 },
  { 66, "gfx6_gfx8", EncodedGcnInstFormatClass::Vopc, 202, 4, "v_cmp_eq_u32_e32", "control", "vector_compare", "vector_alu", kGcnInstFlagNone, 7, 0, 175, 3 },
  { 67, "gfx6_gfx8", EncodedGcnInstFormatClass::Vop3p, 69, 8, "v_mfma_f32_16x16x4f32", "compute", "vector_alu", "vector_alu", kGcnInstFlagIsMatrix, 7, 1, 178, 4 },
  { 85, "gfx6_gfx8", EncodedGcnInstFormatClass::Vop3p, 73, 8, "v_mfma_f32_16x16x4f16", "compute", "vector_alu", "vector_alu", kGcnInstFlagIsMatrix, 8, 1, 182, 4 },
  { 86, "gfx6_gfx8", EncodedGcnInstFormatClass::Vop3p, 81, 8, "v_mfma_i32_16x16x4i8", "compute", "vector_alu", "vector_alu", kGcnInstFlagIsMatrix, 9, 1, 186, 4 },
  { 87, "gfx6_gfx8", EncodedGcnInstFormatClass::Vop3p, 105, 8, "v_mfma_f32_16x16x2bf16", "compute", "vector_alu", "vector_alu", kGcnInstFlagIsMatrix, 10, 1, 190, 4 },
  { 88, "gfx6_gfx8", EncodedGcnInstFormatClass::Vop3p, 68, 8, "v_mfma_f32_32x32x2f32", "compute", "vector_alu", "vector_alu", kGcnInstFlagIsMatrix, 11, 1, 194, 4 },
  { 89, "gfx6_gfx8", EncodedGcnInstFormatClass::Vop3p, 85, 8, "v_mfma_i32_16x16x16i8", "compute", "vector_alu", "vector_alu", kGcnInstFlagIsMatrix, 12, 1, 198, 4 },
  { 90, "gfx6_gfx8", EncodedGcnInstFormatClass::Vop3p, 88, 8, "v_accvgpr_read_b32", "compute", "vector_alu", "vector_alu", kGcnInstFlagNone, 13, 0, 202, 2 },
  { 91, "gfx6_gfx8", EncodedGcnInstFormatClass::Vop3p, 89, 8, "v_accvgpr_write_b32", "compute", "vector_alu", "vector_alu", kGcnInstFlagNone, 13, 0, 204, 2 },
  { 68, "gfx6_gfx8", EncodedGcnInstFormatClass::Sopp, 0, 4, "s_nop", "sync", "branch_or_sync", "branch_or_special", kGcnInstFlagNone, 13, 0, 206, 0 },
  { 69, "gfx6_gfx8", EncodedGcnInstFormatClass::Sop2, 0, 4, "s_add_u32", "compute", "scalar_alu", "scalar_alu_or_memory", kGcnInstFlagNone, 13, 0, 206, 3 },
  { 70, "gfx6_gfx8", EncodedGcnInstFormatClass::Sop2, 4, 4, "s_addc_u32", "compute", "scalar_alu", "scalar_alu_or_memory", kGcnInstFlagNone, 13, 0, 209, 3 },
  { 71, "gfx6_gfx8", EncodedGcnInstFormatClass::Sop1, 1, 4, "s_mov_b64", "compute", "scalar_alu", "scalar_alu_or_memory", kGcnInstFlagNone, 13, 0, 212, 2 },
  { 72, "gfx6_gfx8", EncodedGcnInstFormatClass::Sop2, 32, 4, "s_ashr_i32", "compute", "scalar_alu", "scalar_alu_or_memory", kGcnInstFlagNone, 13, 0, 214, 3 },
  { 73, "gfx6_gfx8", EncodedGcnInstFormatClass::Sop2, 29, 4, "s_lshl_b64", "compute", "scalar_alu", "scalar_alu_or_memory", kGcnInstFlagNone, 13, 0, 217, 3 },
  { 74, "gfx6_gfx8", EncodedGcnInstFormatClass::Sopp, 9, 4, "s_cbranch_execnz", "sync", "branch_or_sync", "branch_or_special", kGcnInstFlagNone, 13, 0, 220, 1 },
  { 75, "gfx6_gfx8", EncodedGcnInstFormatClass::Vopc, 195, 4, "v_cmp_le_i32_e32", "control", "vector_compare", "vector_alu", kGcnInstFlagNone, 13, 0, 221, 3 },
  { 76, "gfx6_gfx8", EncodedGcnInstFormatClass::Vopc, 193, 4, "v_cmp_lt_i32_e32", "control", "vector_compare", "vector_alu", kGcnInstFlagNone, 13, 0, 224, 3 },
  { 77, "gfx6_gfx8", EncodedGcnInstFormatClass::Sop2, 13, 4, "s_and_b64", "compute", "scalar_alu", "scalar_alu_or_memory", kGcnInstFlagNone, 13, 0, 227, 3 },
  { 78, "gfx6_gfx8", EncodedGcnInstFormatClass::Sopk, 0, 4, "s_movk_i32", "compute", "scalar_alu", "scalar_alu_or_memory", kGcnInstFlagNone, 13, 0, 230, 2 },
  { 79, "gfx6_gfx8", EncodedGcnInstFormatClass::Vop3a, 244, 8, "v_mad_u64_u32", "compute", "vector_alu", "vector_alu", kGcnInstFlagNone, 13, 0, 232, 5 },
  { 80, "gfx6_gfx8", EncodedGcnInstFormatClass::Vop1, 5, 4, "v_cvt_f32_i32_e32", "compute", "vector_alu", "vector_alu", kGcnInstFlagNone, 13, 0, 237, 2 },
  { 81, "gfx6_gfx8", EncodedGcnInstFormatClass::Vop3a, 326, 8, "v_mbcnt_lo_u32_b32", "compute", "vector_alu", "vector_alu", kGcnInstFlagNone, 13, 0, 239, 3 },
  { 82, "gfx6_gfx8", EncodedGcnInstFormatClass::Vop3a, 326, 8, "v_mbcnt_hi_u32_b32", "compute", "vector_alu", "vector_alu", kGcnInstFlagNone, 13, 0, 242, 3 },
  { 83, "gfx6_gfx8", EncodedGcnInstFormatClass::Sop1, 13, 4, "s_bcnt1_i32_b64", "compute", "scalar_alu", "scalar_alu_or_memory", kGcnInstFlagNone, 13, 0, 245, 2 },
  { 84, "gfx6_gfx8", EncodedGcnInstFormatClass::Flat, 66, 8, "global_atomic_add", "memory", "vector_memory", "vector_memory", kGcnInstFlagIsMemory | kGcnInstFlagIsAtomic, 13, 1, 247, 3 }
  };
  return kInstDefs;
}

const std::vector<EncodedGcnEncodingDef>& GeneratedGcnEncodingDefs() {
  static const std::vector<EncodedGcnEncodingDef> kEncodingDefs = {
  EncodedGcnEncodingDef{ .id = 1, .format_class = EncodedGcnInstFormatClass::Sopp, .op = 1, .size_bytes = 4, .mnemonic = "s_endpgm" },
  EncodedGcnEncodingDef{ .id = 2, .format_class = EncodedGcnInstFormatClass::Smrd, .op = 0, .size_bytes = 8, .mnemonic = "s_load_dword" },
  EncodedGcnEncodingDef{ .id = 3, .format_class = EncodedGcnInstFormatClass::Smrd, .op = 32, .size_bytes = 8, .mnemonic = "s_load_dwordx2" },
  EncodedGcnEncodingDef{ .id = 4, .format_class = EncodedGcnInstFormatClass::Smrd, .op = 64, .size_bytes = 8, .mnemonic = "s_load_dwordx4" },
  EncodedGcnEncodingDef{ .id = 5, .format_class = EncodedGcnInstFormatClass::Sop2, .op = 12, .size_bytes = 4, .mnemonic = "s_and_b32" },
  EncodedGcnEncodingDef{ .id = 6, .format_class = EncodedGcnInstFormatClass::Sop2, .op = 36, .size_bytes = 4, .mnemonic = "s_mul_i32" },
  EncodedGcnEncodingDef{ .id = 7, .format_class = EncodedGcnInstFormatClass::Vop2, .op = 52, .size_bytes = 4, .mnemonic = "v_add_u32_e32" },
  EncodedGcnEncodingDef{ .id = 8, .format_class = EncodedGcnInstFormatClass::Vopc, .op = 196, .size_bytes = 4, .mnemonic = "v_cmp_gt_i32_e32" },
  EncodedGcnEncodingDef{ .id = 9, .format_class = EncodedGcnInstFormatClass::Sop1, .op = 32, .size_bytes = 4, .mnemonic = "s_and_saveexec_b64" },
  EncodedGcnEncodingDef{ .id = 10, .format_class = EncodedGcnInstFormatClass::Sopp, .op = 8, .size_bytes = 4, .mnemonic = "s_cbranch_execz" },
  EncodedGcnEncodingDef{ .id = 11, .format_class = EncodedGcnInstFormatClass::Vop2, .op = 1, .size_bytes = 4, .mnemonic = "v_add_f32_e32" },
  EncodedGcnEncodingDef{ .id = 12, .format_class = EncodedGcnInstFormatClass::Sopp, .op = 12, .size_bytes = 4, .mnemonic = "s_waitcnt" },
  EncodedGcnEncodingDef{ .id = 13, .format_class = EncodedGcnInstFormatClass::Vop1, .op = 1, .size_bytes = 4, .mnemonic = "v_mov_b32_e32" },
  EncodedGcnEncodingDef{ .id = 14, .format_class = EncodedGcnInstFormatClass::Vop2, .op = 17, .size_bytes = 4, .mnemonic = "v_ashrrev_i32_e32" },
  EncodedGcnEncodingDef{ .id = 15, .format_class = EncodedGcnInstFormatClass::Vop2, .op = 25, .size_bytes = 4, .mnemonic = "v_add_co_u32_e32" },
  EncodedGcnEncodingDef{ .id = 16, .format_class = EncodedGcnInstFormatClass::Vop2, .op = 28, .size_bytes = 4, .mnemonic = "v_addc_co_u32_e32" },
  EncodedGcnEncodingDef{ .id = 17, .format_class = EncodedGcnInstFormatClass::Vop3a, .op = 327, .size_bytes = 8, .mnemonic = "v_lshlrev_b64" },
  EncodedGcnEncodingDef{ .id = 18, .format_class = EncodedGcnInstFormatClass::Flat, .op = 20, .size_bytes = 8, .mnemonic = "global_load_dword" },
  EncodedGcnEncodingDef{ .id = 19, .format_class = EncodedGcnInstFormatClass::Flat, .op = 28, .size_bytes = 8, .mnemonic = "global_store_dword" },
  EncodedGcnEncodingDef{ .id = 20, .format_class = EncodedGcnInstFormatClass::Sop2, .op = 12, .size_bytes = 8, .mnemonic = "s_and_b32" },
  EncodedGcnEncodingDef{ .id = 21, .format_class = EncodedGcnInstFormatClass::Sopc, .op = 4, .size_bytes = 4, .mnemonic = "s_cmp_lt_i32" },
  EncodedGcnEncodingDef{ .id = 22, .format_class = EncodedGcnInstFormatClass::Sopp, .op = 5, .size_bytes = 4, .mnemonic = "s_cbranch_scc1" },
  EncodedGcnEncodingDef{ .id = 23, .format_class = EncodedGcnInstFormatClass::Sop2, .op = 2, .size_bytes = 4, .mnemonic = "s_add_i32" },
  EncodedGcnEncodingDef{ .id = 24, .format_class = EncodedGcnInstFormatClass::Sopc, .op = 6, .size_bytes = 4, .mnemonic = "s_cmp_eq_u32" },
  EncodedGcnEncodingDef{ .id = 25, .format_class = EncodedGcnInstFormatClass::Vop3a, .op = 229, .size_bytes = 8, .mnemonic = "v_fma_f32" },
  EncodedGcnEncodingDef{ .id = 26, .format_class = EncodedGcnInstFormatClass::Sopp, .op = 4, .size_bytes = 4, .mnemonic = "s_cbranch_scc0" },
  EncodedGcnEncodingDef{ .id = 27, .format_class = EncodedGcnInstFormatClass::Sopp, .op = 2, .size_bytes = 4, .mnemonic = "s_branch" },
  EncodedGcnEncodingDef{ .id = 28, .format_class = EncodedGcnInstFormatClass::Sop2, .op = 15, .size_bytes = 4, .mnemonic = "s_or_b64" },
  EncodedGcnEncodingDef{ .id = 29, .format_class = EncodedGcnInstFormatClass::Sopp, .op = 10, .size_bytes = 4, .mnemonic = "s_barrier" },
  EncodedGcnEncodingDef{ .id = 30, .format_class = EncodedGcnInstFormatClass::Ds, .op = 13, .size_bytes = 8, .mnemonic = "ds_write_b32" },
  EncodedGcnEncodingDef{ .id = 31, .format_class = EncodedGcnInstFormatClass::Ds, .op = 54, .size_bytes = 8, .mnemonic = "ds_read_b32" },
  EncodedGcnEncodingDef{ .id = 32, .format_class = EncodedGcnInstFormatClass::Vop1, .op = 43, .size_bytes = 4, .mnemonic = "v_not_b32_e32" },
  EncodedGcnEncodingDef{ .id = 33, .format_class = EncodedGcnInstFormatClass::Vop2, .op = 18, .size_bytes = 4, .mnemonic = "v_lshlrev_b32_e32" },
  EncodedGcnEncodingDef{ .id = 34, .format_class = EncodedGcnInstFormatClass::Vop3a, .op = 254, .size_bytes = 8, .mnemonic = "v_lshl_add_u32" },
  EncodedGcnEncodingDef{ .id = 35, .format_class = EncodedGcnInstFormatClass::Vop3a, .op = 140, .size_bytes = 8, .mnemonic = "v_add_co_u32_e64" },
  EncodedGcnEncodingDef{ .id = 36, .format_class = EncodedGcnInstFormatClass::Vop3a, .op = 142, .size_bytes = 8, .mnemonic = "v_addc_co_u32_e64" },
  EncodedGcnEncodingDef{ .id = 37, .format_class = EncodedGcnInstFormatClass::Vop1, .op = 1, .size_bytes = 8, .mnemonic = "v_mov_b32_e32" },
  EncodedGcnEncodingDef{ .id = 38, .format_class = EncodedGcnInstFormatClass::Vop3a, .op = 98, .size_bytes = 8, .mnemonic = "v_cmp_gt_i32_e64" },
  EncodedGcnEncodingDef{ .id = 39, .format_class = EncodedGcnInstFormatClass::Sopc, .op = 8, .size_bytes = 4, .mnemonic = "s_cmp_gt_u32" },
  EncodedGcnEncodingDef{ .id = 40, .format_class = EncodedGcnInstFormatClass::Sopc, .op = 10, .size_bytes = 4, .mnemonic = "s_cmp_lt_u32" },
  EncodedGcnEncodingDef{ .id = 41, .format_class = EncodedGcnInstFormatClass::Sop2, .op = 11, .size_bytes = 4, .mnemonic = "s_cselect_b64" },
  EncodedGcnEncodingDef{ .id = 42, .format_class = EncodedGcnInstFormatClass::Sop2, .op = 19, .size_bytes = 4, .mnemonic = "s_andn2_b64" },
  EncodedGcnEncodingDef{ .id = 43, .format_class = EncodedGcnInstFormatClass::Sopp, .op = 6, .size_bytes = 4, .mnemonic = "s_cbranch_vccz" },
  EncodedGcnEncodingDef{ .id = 44, .format_class = EncodedGcnInstFormatClass::Vop2, .op = 2, .size_bytes = 4, .mnemonic = "v_sub_f32_e32" },
  EncodedGcnEncodingDef{ .id = 45, .format_class = EncodedGcnInstFormatClass::Vop2, .op = 5, .size_bytes = 8, .mnemonic = "v_mul_f32_e32" },
  EncodedGcnEncodingDef{ .id = 46, .format_class = EncodedGcnInstFormatClass::Vop2, .op = 11, .size_bytes = 4, .mnemonic = "v_max_f32_e32" },
  EncodedGcnEncodingDef{ .id = 47, .format_class = EncodedGcnInstFormatClass::Vop2, .op = 59, .size_bytes = 8, .mnemonic = "v_fmac_f32_e32" },
  EncodedGcnEncodingDef{ .id = 48, .format_class = EncodedGcnInstFormatClass::Vop2, .op = 0, .size_bytes = 4, .mnemonic = "v_cndmask_b32_e32" },
  EncodedGcnEncodingDef{ .id = 49, .format_class = EncodedGcnInstFormatClass::Vop1, .op = 8, .size_bytes = 4, .mnemonic = "v_cvt_i32_f32_e32" },
  EncodedGcnEncodingDef{ .id = 50, .format_class = EncodedGcnInstFormatClass::Vop1, .op = 30, .size_bytes = 4, .mnemonic = "v_rndne_f32_e32" },
  EncodedGcnEncodingDef{ .id = 51, .format_class = EncodedGcnInstFormatClass::Vop1, .op = 32, .size_bytes = 4, .mnemonic = "v_exp_f32_e32" },
  EncodedGcnEncodingDef{ .id = 52, .format_class = EncodedGcnInstFormatClass::Vop1, .op = 34, .size_bytes = 4, .mnemonic = "v_rcp_f32_e32" },
  EncodedGcnEncodingDef{ .id = 53, .format_class = EncodedGcnInstFormatClass::Sop1, .op = 0, .size_bytes = 4, .mnemonic = "s_mov_b32" },
  EncodedGcnEncodingDef{ .id = 54, .format_class = EncodedGcnInstFormatClass::Sop1, .op = 0, .size_bytes = 8, .mnemonic = "s_mov_b32" },
  EncodedGcnEncodingDef{ .id = 55, .format_class = EncodedGcnInstFormatClass::Sop2, .op = 30, .size_bytes = 4, .mnemonic = "s_lshr_b32" },
  EncodedGcnEncodingDef{ .id = 56, .format_class = EncodedGcnInstFormatClass::Vopc, .op = 204, .size_bytes = 4, .mnemonic = "v_cmp_gt_u32_e32" },
  EncodedGcnEncodingDef{ .id = 57, .format_class = EncodedGcnInstFormatClass::Vopc, .op = 75, .size_bytes = 4, .mnemonic = "v_cmp_ngt_f32_e32" },
  EncodedGcnEncodingDef{ .id = 58, .format_class = EncodedGcnInstFormatClass::Vopc, .op = 78, .size_bytes = 4, .mnemonic = "v_cmp_nlt_f32_e32" },
  EncodedGcnEncodingDef{ .id = 59, .format_class = EncodedGcnInstFormatClass::Vop3a, .op = 128, .size_bytes = 8, .mnemonic = "v_cndmask_b32_e64" },
  EncodedGcnEncodingDef{ .id = 60, .format_class = EncodedGcnInstFormatClass::Vop3a, .op = 239, .size_bytes = 8, .mnemonic = "v_div_fixup_f32" },
  EncodedGcnEncodingDef{ .id = 61, .format_class = EncodedGcnInstFormatClass::Vop3a, .op = 240, .size_bytes = 8, .mnemonic = "v_div_scale_f32" },
  EncodedGcnEncodingDef{ .id = 62, .format_class = EncodedGcnInstFormatClass::Vop3a, .op = 241, .size_bytes = 8, .mnemonic = "v_div_fmas_f32" },
  EncodedGcnEncodingDef{ .id = 63, .format_class = EncodedGcnInstFormatClass::Vop3a, .op = 324, .size_bytes = 8, .mnemonic = "v_ldexp_f32" },
  EncodedGcnEncodingDef{ .id = 64, .format_class = EncodedGcnInstFormatClass::Vop2, .op = 5, .size_bytes = 4, .mnemonic = "v_mul_f32_e32" },
  EncodedGcnEncodingDef{ .id = 65, .format_class = EncodedGcnInstFormatClass::Vop2, .op = 59, .size_bytes = 4, .mnemonic = "v_fmac_f32_e32" },
  EncodedGcnEncodingDef{ .id = 66, .format_class = EncodedGcnInstFormatClass::Vopc, .op = 202, .size_bytes = 4, .mnemonic = "v_cmp_eq_u32_e32" },
  EncodedGcnEncodingDef{ .id = 67, .format_class = EncodedGcnInstFormatClass::Vop3p, .op = 69, .size_bytes = 8, .mnemonic = "v_mfma_f32_16x16x4f32" },
  EncodedGcnEncodingDef{ .id = 85, .format_class = EncodedGcnInstFormatClass::Vop3p, .op = 73, .size_bytes = 8, .mnemonic = "v_mfma_f32_16x16x4f16" },
  EncodedGcnEncodingDef{ .id = 86, .format_class = EncodedGcnInstFormatClass::Vop3p, .op = 81, .size_bytes = 8, .mnemonic = "v_mfma_i32_16x16x4i8" },
  EncodedGcnEncodingDef{ .id = 87, .format_class = EncodedGcnInstFormatClass::Vop3p, .op = 105, .size_bytes = 8, .mnemonic = "v_mfma_f32_16x16x2bf16" },
  EncodedGcnEncodingDef{ .id = 88, .format_class = EncodedGcnInstFormatClass::Vop3p, .op = 68, .size_bytes = 8, .mnemonic = "v_mfma_f32_32x32x2f32" },
  EncodedGcnEncodingDef{ .id = 89, .format_class = EncodedGcnInstFormatClass::Vop3p, .op = 85, .size_bytes = 8, .mnemonic = "v_mfma_i32_16x16x16i8" },
  EncodedGcnEncodingDef{ .id = 90, .format_class = EncodedGcnInstFormatClass::Vop3p, .op = 88, .size_bytes = 8, .mnemonic = "v_accvgpr_read_b32" },
  EncodedGcnEncodingDef{ .id = 91, .format_class = EncodedGcnInstFormatClass::Vop3p, .op = 89, .size_bytes = 8, .mnemonic = "v_accvgpr_write_b32" },
  EncodedGcnEncodingDef{ .id = 68, .format_class = EncodedGcnInstFormatClass::Sopp, .op = 0, .size_bytes = 4, .mnemonic = "s_nop" },
  EncodedGcnEncodingDef{ .id = 69, .format_class = EncodedGcnInstFormatClass::Sop2, .op = 0, .size_bytes = 4, .mnemonic = "s_add_u32" },
  EncodedGcnEncodingDef{ .id = 70, .format_class = EncodedGcnInstFormatClass::Sop2, .op = 4, .size_bytes = 4, .mnemonic = "s_addc_u32" },
  EncodedGcnEncodingDef{ .id = 71, .format_class = EncodedGcnInstFormatClass::Sop1, .op = 1, .size_bytes = 4, .mnemonic = "s_mov_b64" },
  EncodedGcnEncodingDef{ .id = 72, .format_class = EncodedGcnInstFormatClass::Sop2, .op = 32, .size_bytes = 4, .mnemonic = "s_ashr_i32" },
  EncodedGcnEncodingDef{ .id = 73, .format_class = EncodedGcnInstFormatClass::Sop2, .op = 29, .size_bytes = 4, .mnemonic = "s_lshl_b64" },
  EncodedGcnEncodingDef{ .id = 74, .format_class = EncodedGcnInstFormatClass::Sopp, .op = 9, .size_bytes = 4, .mnemonic = "s_cbranch_execnz" },
  EncodedGcnEncodingDef{ .id = 75, .format_class = EncodedGcnInstFormatClass::Vopc, .op = 195, .size_bytes = 4, .mnemonic = "v_cmp_le_i32_e32" },
  EncodedGcnEncodingDef{ .id = 76, .format_class = EncodedGcnInstFormatClass::Vopc, .op = 193, .size_bytes = 4, .mnemonic = "v_cmp_lt_i32_e32" },
  EncodedGcnEncodingDef{ .id = 77, .format_class = EncodedGcnInstFormatClass::Sop2, .op = 13, .size_bytes = 4, .mnemonic = "s_and_b64" },
  EncodedGcnEncodingDef{ .id = 78, .format_class = EncodedGcnInstFormatClass::Sopk, .op = 0, .size_bytes = 4, .mnemonic = "s_movk_i32" },
  EncodedGcnEncodingDef{ .id = 79, .format_class = EncodedGcnInstFormatClass::Vop3a, .op = 244, .size_bytes = 8, .mnemonic = "v_mad_u64_u32" },
  EncodedGcnEncodingDef{ .id = 80, .format_class = EncodedGcnInstFormatClass::Vop1, .op = 5, .size_bytes = 4, .mnemonic = "v_cvt_f32_i32_e32" },
  EncodedGcnEncodingDef{ .id = 81, .format_class = EncodedGcnInstFormatClass::Vop3a, .op = 326, .size_bytes = 8, .mnemonic = "v_mbcnt_lo_u32_b32" },
  EncodedGcnEncodingDef{ .id = 82, .format_class = EncodedGcnInstFormatClass::Vop3a, .op = 326, .size_bytes = 8, .mnemonic = "v_mbcnt_hi_u32_b32" },
  EncodedGcnEncodingDef{ .id = 83, .format_class = EncodedGcnInstFormatClass::Sop1, .op = 13, .size_bytes = 4, .mnemonic = "s_bcnt1_i32_b64" },
  EncodedGcnEncodingDef{ .id = 84, .format_class = EncodedGcnInstFormatClass::Flat, .op = 66, .size_bytes = 8, .mnemonic = "global_atomic_add" }
  };
  return kEncodingDefs;
}

}  // namespace gpu_model
